GET http://localhost:4000/health_check

###
POST  http://localhost:4000/api/organizations
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTcxYTA2YThhNjBlY2FlMmEwNTRkYzgiLCJpYXQiOjE2MzY2MzY3NDksImV4cCI6MTYzNjY0MDM0OX0.hyJ3hl8C36sTriSVXifeB0p3V8jrUSbrPH54ijQfVV0

{
"name": "Juanito",
"description": "Best Juanito",
"url": "www.google.com",
"code": "1234",
"type": "store2"
}

###
DELETE http://localhost:4000/api/organizations/618d1882f6ff9999ff6f7c12
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTcxYTA2YThhNjBlY2FlMmEwNTRkYzgiLCJpYXQiOjE2MzY2MzY3NDksImV4cCI6MTYzNjY0MDM0OX0.hyJ3hl8C36sTriSVXifeB0p3V8jrUSbrPH54ijQfVV0

###
GET http://localhost:4000/api/organizations
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTcxYTA2YThhNjBlY2FlMmEwNTRkYzgiLCJpYXQiOjE2MzY2MzY3NDksImV4cCI6MTYzNjY0MDM0OX0.hyJ3hl8C36sTriSVXifeB0p3V8jrUSbrPH54ijQfVV0

###
GET http://localhost:4000/api/organizations?name=Bookstoreupdate
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTcxYTA2YThhNjBlY2FlMmEwNTRkYzgiLCJpYXQiOjE2MzY2MzY3NDksImV4cCI6MTYzNjY0MDM0OX0.hyJ3hl8C36sTriSVXifeB0p3V8jrUSbrPH54ijQfVV0

###
GET http://localhost:4000/api/organizations?code=1234
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTcxYTA2YThhNjBlY2FlMmEwNTRkYzgiLCJpYXQiOjE2MzY2MzY3NDksImV4cCI6MTYzNjY0MDM0OX0.hyJ3hl8C36sTriSVXifeB0p3V8jrUSbrPH54ijQfVV0

###
PATCH http://localhost:4000/api/organizations/618d1898f6ff9999ff6f7c18
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTcxYTA2YThhNjBlY2FlMmEwNTRkYzgiLCJpYXQiOjE2MzY2MzY3NDksImV4cCI6MTYzNjY0MDM0OX0.hyJ3hl8C36sTriSVXifeB0p3V8jrUSbrPH54ijQfVV0

{
    "name": "Bookstoreupdate",
    "description": "Best Bookstore update",
    "url": "www.bookupdate.com",
    "code": "111update",
    "type": "store1update"
}

###
POST  http://localhost:4000/api/user
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTcxYTA2YThhNjBlY2FlMmEwNTRkYzgiLCJpYXQiOjE2MzY2MzY3NDksImV4cCI6MTYzNjY0MDM0OX0.hyJ3hl8C36sTriSVXifeB0p3V8jrUSbrPH54ijQfVV0

{
"email": "test@gmail.com",
"password": "1234567"
}

###
POST  http://localhost:4000/api/user/login
Content-Type: application/json

{
"email": "test@gmail.com",
"password": "1234567"
}

###
GET http://localhost:4000/api/users
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTcxYTA2YThhNjBlY2FlMmEwNTRkYzgiLCJpYXQiOjE2MzY2MzY3NDksImV4cCI6MTYzNjY0MDM0OX0.hyJ3hl8C36sTriSVXifeB0p3V8jrUSbrPH54ijQfVV0
